<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Alteracion_Productos.aspx.cs" Inherits="Vista.CargarProductos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style3 {
            width: 146px;
            font-size: x-large;
            text-align: center;
        }
        .auto-style4 {
            width: 146px;
            text-align: right;
        }
        .auto-style5 {
            width: 146px;
            height: 26px;
            text-align: right;
        }
        .auto-style6 {
            height: 26px;
        }
        .auto-style7 {
            margin-left: 148px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gvProductos" runat="server" AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="ID_Producto" PageSize="14" OnPageIndexChanging="gvProductos_PageIndexChanging" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="gvProductos_RowCancelingEdit" OnRowDeleting="gvProductos_RowDeleting" OnRowEditing="gvProductos_RowEditing" OnRowUpdating="gvProductos_RowUpdating">
                <Columns>
                    <asp:TemplateField HeaderText="ID_Producto">
                        <ItemTemplate>
                            <asp:Label ID="lbl_IdProducto" runat="server" Text='<%# Bind("ID_Producto") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_Nombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Nombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripcion">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_Descripcion" runat="server" Text='<%# Bind("Descripcion") %>' Width="193px"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Descripcion" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Tipo_Producto">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_TipoProducto" runat="server" Text='<%# Bind("Tipo_Producto") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_producto" runat="server" Text='<%# Bind("Tipo_Producto") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Stock">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_Stock" runat="server" Text='<%# Bind("Stock") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Stock" runat="server" Text='<%# Bind("Stock") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio_Compra">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_PrecioCompra" runat="server" Text='<%# Bind("Precio_Compra") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_PrecioCompra" runat="server" Text='<%# Bind("Precio_Compra") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio_Venta">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_PrecioVenta" runat="server" Text='<%# Bind("Precio_Venta") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Precio_Venta" runat="server" Text='<%# Bind("Precio_Venta") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Img_URL">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_imgURL" runat="server" Text='<%# Bind("Img_URL") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_imgURL" runat="server" Text='<%# Bind("Img_URL") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Estado">
                        <EditItemTemplate>
                            <asp:CheckBox ID="chk_Estado" runat="server" Checked="True" Text='<%# Bind("Estado") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:CheckBox ID="CheckBox1" runat="server" Checked='<%# Bind("Estado") %>' />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EmptyDataTemplate>
                    <asp:Label ID="lblIdProducto" runat="server" Text='<%# Bind("ID_Producto") %>'></asp:Label>
                </EmptyDataTemplate>
            </asp:GridView>
            <br />
            <table class="auto-style1">
                <tr>
                    <td class="auto-style3"><strong>Agregar Producto</strong></td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style4">Nombre:</td>
                    <td>
                        <asp:TextBox ID="txtNombre" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style4">Descripcion:</td>
                    <td>
                        <asp:TextBox ID="txtDesc" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style5">Tipo producto:</td>
                    <td class="auto-style6">
                        <asp:DropDownList ID="Ddl_TipoProd" runat="server">
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style5">Stock:</td>
                    <td class="auto-style6">
                        <asp:TextBox ID="txtStock" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style4">Precio Compra:</td>
                    <td>
                        <asp:TextBox ID="txtPrecioCompra" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style4">Precio Venta:</td>
                    <td>
                        <asp:TextBox ID="txtPrecioVenta" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style4">Img URL:</td>
                    <td>
                        <asp:TextBox ID="txtImgURL" runat="server"></asp:TextBox>
                    </td>
                </tr>
            </table>
            <br />
            <br />
            <asp:Button ID="btn_aceptar" runat="server" CssClass="auto-style7" OnClick="btn_aceptar_Click" Text="Agregar" Width="140px" />
        </div>
    </form>
</body>
</html>
